language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - pip install clint
  - pip install .
script:
  - nosetests
  # nose doesn't like the number on test_e2e so it's not detected by the
  # previous command.
  - nosetests gitless/tests/test_e2e.py
branches:
  except:
    - master
